### ISSUE TITLE
Update mstatus.h, sstatus.h, mstatush.h with new fields

### ISSUE THREAD

**Issue by mmhus** [mmoizhussain/riscv-sbi-basic#28]
There are some extra fields defined for the hypervisor extension in sections 8.4 and 8.2.11 in the riscv-privileged spec, sstatus.h would be the same as vsstatus.h (don't create a header for vsstatus).

Deadline: 5th April 2022

**Comment by Rabbiya-Noor** [comment]
https://github.com/mmoizhussain/riscv-sbi-basic/pull/31
